server:
  port: 9080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://myahsuexvmnijt:2608b338abec449c3e8538d78bb644a2489a528c58e194443034eeee1ad1f782@ec2-18-214-195-34.compute-1.amazonaws.com:5432/d90nvumh63l6sg
    username: myahsuexvmnijt
    password: 2608b338abec449c3e8538d78bb644a2489a528c58e194443034eeee1ad1f782
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp Dio - Santander
  version: 1.2